### ISSUE TITLE
paddlelabel 启动失败

### ISSUE THREAD

**Issue by DD384789980** [PaddleCV-SIG/PP-Label#168]
错误提示：
Traceback (most recent call last):
  File "/usr/local/bin/paddlelabel", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/__main__.py", line 108, in run
    from paddlelabel.api.controller.sample import prep_samples
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/api/controller/sample.py", line 11, in <module>
    from paddlelabel.api.schema import ProjectSchema
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/api/schema/__init__.py", line 2, in <module>
    from .project import ProjectSchema
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/api/schema/project.py", line 11, in <module>
    class ProjectSchema(BaseSchema):
  File "/usr/local/lib/python3.10/dist-packages/marshmallow/schema.py", line 121, in __new__
    klass._declared_fields = mcs.get_declared_fields(
  File "/usr/local/lib/python3.10/dist-packages/marshmallow_sqlalchemy/schema.py", line 91, in get_declared_fields
    fields.update(mcs.get_declared_sqla_fields(fields, converter, opts, dict_cls))
  File "/usr/local/lib/python3.10/dist-packages/marshmallow_sqlalchemy/schema.py", line 130, in get_declared_sqla_fields
    converter.fields_for_model(
  File "/usr/local/lib/python3.10/dist-packages/marshmallow_sqlalchemy/convert.py", line 154, in fields_for_model
    field = base_fields.get(key) or self.property2field(prop)
  File "/usr/local/lib/python3.10/dist-packages/marshmallow_sqlalchemy/convert.py", line 193, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/usr/local/lib/python3.10/dist-packages/marshmallow_sqlalchemy/convert.py", line 275, in _get_field_class_for_property
    column = _base_column(prop.columns[0])
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 1329, in __getattr__
    return self._fallback_getattr(key)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 1298, in _fallback_getattr
    raise AttributeError(key)
AttributeError: columns

**Comment by DD384789980** [comment]
Starting PaddleLabel
INFO  [paddlelabel.config.19]: Database path: sqlite:////root/.paddlelabel/paddlelabel.db
Traceback (most recent call last):
  File "/usr/local/bin/paddlelabel", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/__main__.py", line 107, in run
    from paddlelabel import api, task
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/api/__init__.py", line 7, in <module>
    from paddlelabel.config import app
  File "/usr/local/lib/python3.10/dist-packages/paddlelabel/config.py", line 31, in <module>
    db = SQLAlchemy(app)
  File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?
