### ISSUE TITLE
启动报错，按照操作说明安装了 paddlelabel 

### ISSUE THREAD

**Issue by jinneigeyu** [PaddleCV-SIG/PP-Label#208]
`(paddlelabel_1) PS C:\Users\Lenovo> pdlabel
Starting PaddleLabel
INFO  [paddlelabel.config.19]: Database path: sqlite:///C:\Users\Lenovo\.paddlelabel\paddlelabel.db
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Scripts\pdlabel.exe\__main__.py", line 7, in <module>
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\paddlelabel\__main__.py", line 107, in run
    from paddlelabel import api, task
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\paddlelabel\api\__init__.py", line 7, in <module>
    from paddlelabel.config import app
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\paddlelabel\config.py", line 21, in <module>
    connexion_app = connexion.App("PaddleLabel")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\connexion\utils.py", line 284, in _delayed_error
    raise type(exc)(msg).with_traceback(exc.__traceback__)
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\connexion\__init__.py", line 19, in <module>
    from connexion.apps.flask import FlaskApi, FlaskApp
  File "C:\Users\Lenovo\.conda\envs\paddlelabel_1\Lib\site-packages\connexion\apps\flask.py", line 11, in <module>
    from a2wsgi import WSGIMiddleware
ModuleNotFoundError: Please install connexion using the 'flask' extra`

**Comment by Carvinhan** [comment]
同样是这个问题，求问怎么解决的呀？

**Comment by Carvinhan** [comment]
请问如何进微信交流群呀？

**Comment by star-dc2022** [comment]
pip install a2wsgi  uvicorn==0.18.1
就可以启动了

**Comment by jinneigeyu** [comment]
都是某些模块版本过高的问题，我这样解决了，可以手动打标了
pip install connexion[flask]
pip install uvicorn==0.20.0

**Comment by danny-zhu** [comment]
> pip install a2wsgi uvicorn==0.18.1 就可以启动了

我也是启动报错：TypeError: run() got an unexpected keyword argument 'debug'
按照上面的办法安装依赖的组件后，可以启动，不过因为是部署在服务器端，通过远程进行访问，还要加上启动参数 --lan就可以远程访问了。
可能是uvicorn的高版本引起的bug，换成低版本的，正常启动。
感谢感谢！

**Comment by star-dc2022** [comment]
https://github.com/PaddleCV-SIG/PaddleLabel/issues/209#issuecomment-1821998030
这是找到的完整的依赖包的版本
-----------------------
pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps

**Comment by gxa1028** [comment]
> pip install a2wsgi uvicorn==0.18.1 就可以启动了

太强了老哥

**Comment by noiiiu** [comment]
> ## [#209 (comment)](https://github.com/PaddleCV-SIG/PaddleLabel/issues/209#issuecomment-1821998030)
> 这是找到的完整的依赖包的版本
> pip install uvicorn==0.14 --no-deps pip install connexion==2.14.1 --no-deps pip install anyio==3.0 --no-deps pip install Werkzeug==2.2.2 --no-deps pip install starlette==0.21.0 --no-deps pip install Flask==2.2.2 --no-deps pip install Flask-Cors==3.0.10 --no-deps pip install a2wsgi==1.8.0 --no-deps pip install alembic==1.12.1 --no-deps

成功works  牛逼

**Comment by oxiran** [comment]
> pip install a2wsgi uvicorn==0.18.1 就可以启动了

nice bro!
