### ISSUE TITLE
创建项目或打开样例项目失败

### ISSUE THREAD

**Issue by fatejzz** [PaddleCV-SIG/PP-Label#209]
这是相关报错信息
ERROR [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\connexion\middleware\main.py", line 483, in __call__
    await self.app(scope, receive, send)
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\connexion\middleware\exceptions.py", line 101, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\starlette\_exception_handler.py", line 63, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Anaconda\envs\paddlelabel\Lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: backend_error() takes 1 positional argument but 2 were given

**Comment by xxwgoodgoodstudy** [comment]
我也碰到了这个问题，请问你解决了吗，不胜感激

**Comment by fatejzz** [comment]
> 我也碰到了这个问题，请问你解决了吗，不胜感激

没有，我之前是启动错误然后按照有个问题的解决方式装了几个包之后可以启动了，但是不能创建项目

**Comment by sdjkxhb2016** [comment]
不知道什么时候能解决，我换成旧版本，也不能创建

**Comment by wang-zhix** [comment]
ERROR [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/connexion/middleware/main.py", line 483, in __call__
    await self.app(scope, receive, send)
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/connexion/middleware/exceptions.py", line 101, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/starlette/_exception_handler.py", line 63, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/zkrj/miniconda3/envs/paddlelabel/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: backend_error() takes 1 positional argument but 2 were given


同样的问题

**Comment by dugudongfangshuo** [comment]
快点解决一下吧

**Comment by wang-zhix** [comment]
包的版本问题
uvicorn==0.14
connexion==2.14.1
anyio==3.0
Werkzeug==2.2.2
starlette==0.21.0
Flask==2.2.2
Flask-Cors==3.0.10
a2wsgi==1.8.0
alembic==1.12.1
以上这些包  使用这些版本 可以正常创建和标注
————————————————————————————————
完整命令如下：
conda create -n paddlelabel python=3.11
conda activate paddlelabel
pip install --upgrade paddlelabel

pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps

在启动的时候  不要使用 --home参数，样例项目的路径不会跟随--home参数（虽然有--home但样例项目依旧在用户目录下）
我的启动命令
paddlelabel --port 55537 --lan

**Comment by wang-zhix** [comment]
[requirements.txt](https://github.com/PaddleCV-SIG/PaddleLabel/files/13432918/requirements.txt)
还有其它报错，可以查看我的requirements.txt

**Comment by danny-zhu** [comment]
> 包的版本问题 uvicorn==0.14 connexion==2.14.1 anyio==3.0 Werkzeug==2.2.2 starlette==0.21.0 Flask==2.2.2 Flask-Cors==3.0.10 a2wsgi==1.8.0 alembic==1.12.1 以上这些包 使用这些版本 可以正常创建和标注 ———————————————————————————————— 完整命令如下： conda create -n paddlelabel python=3.11 conda activate paddlelabel pip install --upgrade paddlelabel
> 
> pip install uvicorn==0.14 --no-deps pip install connexion==2.14.1 --no-deps pip install anyio==3.0 --no-deps pip install Werkzeug==2.2.2 --no-deps pip install starlette==0.21.0 --no-deps pip install Flask==2.2.2 --no-deps pip install Flask-Cors==3.0.10 --no-deps pip install a2wsgi==1.8.0 --no-deps pip install alembic==1.12.1 --no-deps
> 
> 在启动的时候 不要使用 --home参数，样例项目的路径不会跟随--home参数（虽然有--home但样例项目依旧在用户目录下） 我的启动命令 paddlelabel --port 55537 --lan

运行项目时报错：TypeError: 'coroutine' object is not callable
ERROR [uvicorn.error] Exception in ASGI application
按照上面的版本重新安装依赖的组件后，可以正常运行项目了！

**Comment by djm-afk** [comment]
> 包的版本问题 uvicorn==0.14 connexion==2.14.1 anyio==3.0 Werkzeug==2.2.2 starlette==0.21.0 Flask==2.2.2 Flask-Cors==3.0.10 a2wsgi==1.8.0 alembic==1.12.1 以上这些包 使用这些版本 可以正常创建和标注 ———————————————————————————————— 完整命令如下： conda create -n paddlelabel python=3.11 conda activate paddlelabel pip install --upgrade paddlelabel
> 
> pip install uvicorn==0.14 --no-deps pip install connexion==2.14.1 --no-deps pip install anyio==3.0 --no-deps pip install Werkzeug==2.2.2 --no-deps pip install starlette==0.21.0 --no-deps pip install Flask==2.2.2 --no-deps pip install Flask-Cors==3.0.10 --no-deps pip install a2wsgi==1.8.0 --no-deps pip install alembic==1.12.1 --no-deps
> 
> 在启动的时候 不要使用 --home参数，样例项目的路径不会跟随--home参数（虽然有--home但样例项目依旧在用户目录下） 我的启动命令 paddlelabel --port 55537 --lan

实测解决问题，谢谢您！
