### ISSUE TITLE
windows系统 python3.11 报错ModuleNotFoundError: Please install connexion using the 'flask' extra

### ISSUE THREAD

**Issue by PlayerJian** [PaddleCV-SIG/PP-Label#221]
Starting PaddleLabel
INFO  [paddlelabel.config.19]: Database path: sqlite:///C:\Users\11742\.paddlelabel\paddlelabel.db
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Scripts\paddlelabel.exe\__main__.py", line 7, in <module>
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\paddlelabel\__main__.py", line 107, in run
    from paddlelabel import api, task
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\paddlelabel\api\__init__.py", line 7, in <module>
    from paddlelabel.config import app
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\paddlelabel\config.py", line 21, in <module>
    connexion_app = connexion.App("PaddleLabel")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\connexion\utils.py", line 284, in _delayed_error
    raise type(exc)(msg).with_traceback(exc.__traceback__)
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\connexion\__init__.py", line 19, in <module>
    from connexion.apps.flask import FlaskApi, FlaskApp
  File "C:\Users\11742\AppData\Local\conda\conda\envs\paddlelabel\Lib\site-packages\connexion\apps\flask.py", line 9, in <module>
    from a2wsgi import WSGIMiddleware
ModuleNotFoundError: Please install connexion using the 'flask' extra

**Comment by jhonboHou** [comment]
执行 pip install connexion[falsk] 试试
