### ISSUE TITLE
win11 安装完启动报错TypeError: run() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by alanOO7** [PaddleCV-SIG/PP-Label#225]
pip 安装完启动报错，
提示    from connexion.apps.flask import FlaskApi, FlaskApp
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Lib\site-packages\connexion\apps\flask.py", line 11, in <module>
    from a2wsgi import WSGIMiddleware
ModuleNotFoundError: Please install connexion using the 'flask' extra
， 通过pip install "connexion[flask]" 安装后启动
提示
Traceback (most recent call last):
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Lib\site-packages\connexion\middleware\main.py", line 475, in run
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
通过 pip install "connexion[uvicorn]" 安装后启动
提示 
INFO  [paddlelabel.config.19]: Database path: sqlite:///C:\Users\mcnalwan\.paddlelabel\paddlelabel.db
INFO  [paddlelabel.__main__.119]: Version: 1.0.1
INFO  [paddlelabel.__main__.120]: PaddleLabel is running at http://localhost:17995
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Scripts\paddlelabel.exe\__main__.py", line 7, in <module>
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Lib\site-packages\paddlelabel\__main__.py", line 122, in run
    connexion_app.run(host=configs.host, port=configs.port, debug=configs.debug)
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Lib\site-packages\connexion\apps\abstract.py", line 281, in run
    self.middleware.run(import_string, **kwargs)
  File "C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddlelabel\Lib\site-packages\connexion\middleware\main.py", line 497, in run
    uvicorn.run(app, **kwargs)
TypeError: run() got an unexpected keyword argument 'debug'

请问如何处理

**Comment by ericosmic** [comment]
linux安装后遇到同样的问题， 怎样解决啊

**Comment by deyinliwork** [comment]
尝试让环境中的`uvicorn`版本为`0.18.1`：

```shell
pip install uvicorn==0.18.1
```
