### ISSUE TITLE
'coroutine' object is not callable

### ISSUE THREAD

**Issue by luxiangyugo** [PaddleCV-SIG/PP-Label#227]
语义分割项目
创建项目，创建不了，弹窗“项目创建失败”
报错如下：
TypeError: 'coroutine' object is not callable
ERROR [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "D:\anaconda3\envs\py310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\anaconda3\envs\py310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\anaconda3\envs\py310\lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "D:\anaconda3\envs\py310\lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "D:\anaconda3\envs\py310\lib\site-packages\connexion\middleware\main.py", line 505, in __call__
    await self.app(scope, receive, send)
  File "D:\anaconda3\envs\py310\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    await response(scope, receive, send)
TypeError: 'coroutine' object is not callable

**Comment by luxiangyugo** [comment]
Found solution:
"
pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps
pip install a2wsgi uvicorn==0.18.1
"

from:
https://github.com/PaddleCV-SIG/PaddleLabel/issues/214#issuecomment-1951036133
