### ISSUE TITLE
无法启动标注工作

### ISSUE THREAD

**Issue by laoding1974** [PaddleCV-SIG/PP-Label#230]
直接**pip** 安装的，启动pdlabel后，点击“样例项目”中的任何一个，后台报错：

Traceback (most recent call last):
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\swagger_ui.py", line 222, in __call__
    await self.router(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 806, in app
    await self.default(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\swagger_ui.py", line 235, in default_fn
    await self.app(original_scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\routing.py", line 154, in __call__
    await self.router(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\routing.py", line 48, in __call__
    await self.next_app(original_scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\security.py", line 106, in __call__
    await self.next_app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\request_validation.py", line 142, in __call__
    await self.next_app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\lifespan.py", line 26, in __call__
    await self.next_app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\context.py", line 25, in __call__
    await self.next_app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\apps\flask.py", line 151, in __call__
    return await self.asgi_app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\a2wsgi\wsgi.py", line 165, in __call__
    return await responder(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\a2wsgi\wsgi.py", line 200, in __call__
    await self.loop.run_in_executor(
  File "C:\Python\miniconda3\envs\paddle-label\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\a2wsgi\wsgi.py", line 256, in wsgi
    iterable = self.app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\apps\flask.py", line 68, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\decorators\main.py", line 134, in wrapper
    return decorated_function(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\decorators\response.py", line 171, in wrapper
    handler_response = function(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\decorators\parameter.py", line 87, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\decorators\main.py", line 123, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\paddlelabel\api\controller\sample.py", line 163, in load_sample
    task_category_id = connexion.request.json.get("task_category_id")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\exceptions.py", line 112, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\_exception_handler.py", line 75, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: backend_error() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\connexion\middleware\main.py", line 505, in __call__
    await self.app(scope, receive, send)
  File "C:\Python\miniconda3\envs\paddle-label\Lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    await response(scope, receive, send)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not callable
[32mINFO[0m:     127.0.0.1:65309 - "[1mPOST /api/samples HTTP/1.1[0m" [91m500 Internal Server Error[0m

**Comment by djm-afk** [comment]
同问，后台报500。

**Comment by siriusforgit** [comment]
你好，请问解决了么？

**Comment by deyinliwork** [comment]
尝试让环境中的`uvicorn`版本为`0.18.1`：

```shell
pip install uvicorn==0.18.1
```
