### ISSUE TITLE
TypeError: argument of type 'method' is not iterable

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#71]
创建项目
报错

所有项目都一样

```

paddlelabel

Database url: sqlite:///C:\Users\mm\.paddlelabel\paddlelabel.db
PaddleLabel is running at http://localhost:17995
 * Serving Flask app 'PaddleLabel'
 * Debug mode: off
Create project failed
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 49, in _import_dataset
    task_category = TaskCategory._get(task_category_id=project.task_category_id)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\model\base.py", line 52, in _get
    if key not in cls._cols:
TypeError: argument of type 'method' is not iterable



TypeError: argument of type 'method' is not iterable
[ERROR]app.1742: Exception on /api/samples [POST]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\decorator.py", line 68, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\validation.py", line 196, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\sample.py", line 142, in load_sample
    task_category = TaskCategory._get(task_category_id=task_category_id)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\model\base.py", line 52, in _get
    if key not in cls._cols:
TypeError: argument of type 'method' is not iterable


```

**Comment by TimZhang001** [comment]
我也一样

**Comment by monkeycc** [comment]
@TimZhang001 

```
\PaddleLabel\lib\site-packages\paddlelabel\api\model\base.py", line 52, in _get
    if key not in cls._cols:
```

把这个 整个for 注释就好了

**Comment by TimZhang001** [comment]
> @TimZhang001
> 
> ```
> \PaddleLabel\lib\site-packages\paddlelabel\api\model\base.py", line 52, in _get
>     if key not in cls._cols:
> ```
> 
> 把这个 整个for 注释就好了

谢谢，我没有用source code，直接pip安装的，谢谢你，我试试

**Comment by linhandev** [comment]
这个感觉可能是sqlalchemy版本的问题，能不能在有这个问题的环境里做一下 `pip list`，看一下 Flask-SQLAlchemy，SQLAlchemy和marshmallow-sqlalchemy的版本，我来试试能不能复现这个问题
@monkeycc @TimZhang001

**Comment by monkeycc** [comment]
```
Package                Version
---------------------- -------------
astor                  0.8.1
attrs                  22.1.0
certifi                2022.6.15
cffi                   1.15.1
charset-normalizer     2.1.0
click                  8.1.3
clickclick             20.10.2
colorama               0.4.5
connexion              2.14.0
cryptography           37.0.4
cycler                 0.11.0
Cython                 0.29.32
decorator              5.1.1
filelock               3.8.0
Flask                  2.2.2
Flask-Cors             3.0.10
flask-marshmallow      0.14.0
Flask-SQLAlchemy       2.5.1
fonttools              4.34.4
greenlet               1.1.2
idna                   3.3
imagecodecs            2021.11.20
importlib-metadata     4.12.0
importlib-resources    5.9.0
inflection             0.5.1
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.9.1
jwt                    1.3.1
kiwisolver             1.4.4
MarkupSafe             2.1.1
marshmallow            3.17.0
marshmallow-sqlalchemy 0.28.1
matplotlib             3.5.3
numpy                  1.21.6
opencv-python          4.6.0.66
opt-einsum             3.3.0
packaging              21.3
paddle-bfloat          0.1.7
paddlelabel            0.1.0
paddlelabel-ml         0.0.31
paddlepaddle-gpu       2.3.1.post116
Pillow                 9.2.0
pip                    22.1.2
pkgutil_resolve_name   1.3.10
protobuf               3.20.1
pycocotoolse           2.0.10
pycparser              2.21
pyparsing              3.0.9
pyrsistent             0.18.1
python-dateutil        2.8.2
PyYAML                 6.0
requests               2.28.1
setuptools             61.2.0
six                    1.16.0
SQLAlchemy             1.4.40
swagger-ui-bundle      0.0.9
tifffile               2021.11.2
tqdm                   4.64.0
typing_extensions      4.3.0
urllib3                1.26.11
uuid                   1.30
Werkzeug               2.2.2
wheel                  0.37.1
wincertstore           0.2
zipp                   3.8.1
```

**Comment by linhandev** [comment]
这个环境下现在还是确定有那个 TypeError: argument of type 'method' is not iterable 问题的是吗，我看版本应该都是最新的，感觉不像版本问题。我在win下也没遇到这个，就很奇怪

**Comment by linhandev** [comment]
话说我在py36里也遇到这问题了，应该跟py版本有关，我们这边开发都是用的py39，可以新开个环境试一下
@monkeycc @TimZhang001

**Comment by monkeycc** [comment]
我这边是 anaconda python 3.7

我直接注释了  就解决了


```

    @classmethod
    def _get(cls, **kwargs):
        many = kwargs.get("many", False)
        if "many" in kwargs.keys():
            del kwargs["many"]
        # for key in kwargs.keys():
        #     if key not in cls._cols:
        #         raise AttributeError(f"Model {cls.__tablename__} don't have attribute {key}")
```

**Comment by linhandev** [comment]
注掉问题不大，这块本来就是个确定调用参数合法。能复现了我看看怎么解决

**Comment by linhandev** [comment]
我看一直到py38都有这问题，被我py39完美避开了 /笑哭

**Comment by linhandev** [comment]
v0.1.1应该是解决了这个问题，可以试一下

**Comment by monkeycc** [comment]
没问题 通过

**Comment by linhandev** [comment]
6的

**Comment by TimZhang001** [comment]
> v0.1.1应该是解决了这个问题，可以试一下
已经测试，通过。不过里面的智能标注的预训练模型是否可以提供一下下载路径呢，以及如何替换成为自己的模型，有没有说明文档呢

**Comment by linhandev** [comment]
>  已经测试，通过。不过里面的智能标注的预训练模型是否可以提供一下下载路径呢，以及如何替换成为自己的模型，有没有说明文档呢

交互式标注需要装一个机器学习后端，[这个文档](https://github.com/PaddleCV-SIG/PaddleLabel/blob/develop/doc/CN/project/interactive_segmentation.md)里有方法和模型下载路径
