### ISSUE TITLE
已有标签的目标检测数据集怎么导入

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#79]
已有的目标数据集,怎么导入

1.jpg
1.xml
2.jpg
2.xml

**Comment by linhandev** [comment]
xml的应该是pascal voc，[参考文档](https://github.com/PaddleCV-SIG/PaddleLabel/blob/develop/doc/CN/project/detection.md#pascal-voc)

**Comment by monkeycc** [comment]
```
[ WARN:0@1264.964] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\MM\1.jpg'): can't open/read file: check file path/integrity
Create project failed
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
    importer(data_dir)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
    s = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

Annotations
JPEGImages
labels.txt

**Comment by monkeycc** [comment]
各种问题

```

PaddleLabel is running at http://localhost:17995
 * Serving Flask app 'PaddleLabel'
 * Debug mode: off
[ WARN:0@1264.964] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\00Biaozhu\yanse_peijian_08\PPCS2\Y_Biaozhu\1.jpg'): can't open/read file: check file path/integrity
Create project failed
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
    importer(data_dir)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
    s = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

[ERROR]app.1742: Exception on /api/projects [POST]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 55, in _import_dataset
    handler = eval(task_category.handler)(project, data_dir=data_dir)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\detection.py", line 134, in __init__
    super(Detection, self).__init__(project, data_dir=data_dir, is_export=is_export)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 61, in __init__
    self.import_labels()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 365, in import_labels
    self.add_label(*label, comment=comment)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 293, in add_label
    id = int(id)
ValueError: invalid literal for int() with base 10: 'mask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\decorator.py", line 68, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\validation.py", line 196, in wrapper
    response = function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\validation.py", line 399, in wrapper
    return function(request)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\connexion\decorators\parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\base.py", line 79, in post
    post_add(new_item, db.session)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 81, in post_add
    db.session.commit()
  File "<string>", line 2, in commit
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 3383, in flush
    self._flush(objects)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\session.py", line 3483, in _flush
    flush_context.execute()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 670, in execute
    uow,
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\persistence.py", line 348, in delete_obj
    delete,
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\orm\persistence.py", line 1469, in _emit_delete_statements
    statement, del_objects, execution_options=execution_options
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    self, multiparams, params, execution_options
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: DELETE FROM project WHERE project.project_id = ?]
[parameters: (9,)]
```

**Comment by linhandev** [comment]
hum，看起来一些跟xml文件有关。数据公开吗，方不方便分享一个有问题的xml

**Comment by monkeycc** [comment]
[1.zip](https://github.com/PaddleCV-SIG/PaddleLabel/files/9398648/1.zip)

图片 1072*522

**Comment by linhandev** [comment]
> ```
> [ WARN:0@1264.964] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\MM\1.jpg'): can't open/read file: check file path/integrity
> Create project failed
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
>     _import_dataset(new_project)
>   File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
>     importer(data_dir)
>   File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
>     s = img.shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```
> 
> Annotations JPEGImages labels.txt

我不是很清楚这个bug怎么回事，按照代码来看这个图片文件应该存在但是cv2读取失败了，所以那个img是none。修复其他问题之后可以再观察还有没有这个问题或者 `[ERROR]detection.465: Load image xx failed` 的cmd报错

**Comment by linhandev** [comment]
```shell
[ERROR]app.1742: Exception on /api/projects [POST]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\api\controller\project.py", line 55, in _import_dataset
    handler = eval(task_category.handler)(project, data_dir=data_dir)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\detection.py", line 134, in __init__
    super(Detection, self).__init__(project, data_dir=data_dir, is_export=is_export)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 61, in __init__
    self.import_labels()
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 365, in import_labels
    self.add_label(*label, comment=comment)
  File "D:\Anaconda3\envs\PaddleLabel\lib\site-packages\paddlelabel\task\base.py", line 293, in add_label
    id = int(id)
ValueError: invalid literal for int() with base 10: 'mask'
```

这个问题是labels.txt文件里的，labels.txt如果是

```text
1 mask
```
这样就会有这个问题。

[这里](https://github.com/PaddleCV-SIG/PaddleLabel/blob/develop/doc/CN/project/common.md#labelstxt)有我们支持的所有labels.txt格式。

![image](https://user-images.githubusercontent.com/29757093/186056447-96236ac0-c105-419c-9ecc-fdee4f3fe2d3.png)

**Comment by monkeycc** [comment]
这里有个问题

是不是标注好的
1.jpg
1.xml
2.jpg
2.xml
或者是
Annotations
JPEGImages

是不是必须先要转换为VOC格式才能导入
必须要
Annotations
JPEGImages
然后进行数据划分

这样才会有之前的标注信息

但是也不提供一键转换voc coco这些
需要用户自己去解决 ？

**Comment by linhandev** [comment]
数据导入之后导出的时候可以选择所有我们支持的格式。我们支持一个格式都是导入导出都支持的。

导入的时候如果想导入标注信息是需要按照一个我们支持的格式去组织数据。没有标注的话就所有图片都扔到一个文件夹下就行了。

**Comment by monkeycc** [comment]
测试通过
几个VOC数据集
导入VOC确实可以


但是有个数据集会提示错误
这个数据集 PaddleDetection能训练通过
但是导入PaddleLabel会报错

```

It's recommended to run PaddleLabel with Python>=3.9.0. Please consider creating a new virtual enviroment and run PaddleLabel with:

conda create -y -n paddlelabel python=3.9
conda activate paddlelabel
pip install --upgrade paddlelabel
paddlelabel


PaddleLabel is running at http://localhost:17995
 * Serving Flask app 'PaddleLabel'
 * Debug mode: off
[ WARN:0@22.365] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\00Biaozhu\OK\10_4.jpg'): can't open/read file: check file path/integrity
Create project failed
Traceback (most recent call last):
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
    importer(data_dir)
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
    s = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```


数据集目录是
F:\00Biaozhu
JPEGImages
Annotations
*.txt

train_list.txt
里面是
JPEGImages\10_4.jpg Annotations\10_4.xml

但是这里报错居然是
F:\00Biaozhu\OK\10_4.jpg

难道是 读取了xml的地址
10_4.xml
<path>F:\00Biaozhu\OK\10_4.jpg</path>

F:\00Biaozhu\OK\
已经被删除

@linhandev

**Comment by monkeycc** [comment]
```
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
```

还有一个数据集报错
但是在paddleX中 可以导入数据集

**Comment by linhandev** [comment]
> ```
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> [ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
> ```
> 
> 还有一个数据集报错 但是在paddleX中 可以导入数据集

这个看着是有点问题，你这跑的是哪个版本，是action的开发版嘛，现在最新的这块输出貌似不是这样的。

**Comment by linhandev** [comment]
> 测试通过 几个VOC数据集 导入VOC确实可以
> 
> 但是有个数据集会提示错误 这个数据集 PaddleDetection能训练通过 但是导入PaddleLabel会报错
> 
> ```
> 
> It's recommended to run PaddleLabel with Python>=3.9.0. Please consider creating a new virtual enviroment and run PaddleLabel with:
> 
> conda create -y -n paddlelabel python=3.9
> conda activate paddlelabel
> pip install --upgrade paddlelabel
> paddlelabel
> 
> 
> PaddleLabel is running at http://localhost:17995
>  * Serving Flask app 'PaddleLabel'
>  * Debug mode: off
> [ WARN:0@22.365] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\00Biaozhu\OK\10_4.jpg'): can't open/read file: check file path/integrity
> Create project failed
> Traceback (most recent call last):
>   File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
>     _import_dataset(new_project)
>   File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
>     importer(data_dir)
>   File "D:\anaconda31114\envs\biaozhu\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
>     s = img.shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```
> 
> 数据集目录是 F:\00Biaozhu JPEGImages Annotations *.txt
> 
> train_list.txt 里面是 JPEGImages\10_4.jpg Annotations\10_4.xml
> 
> 但是这里报错居然是 F:\00Biaozhu\OK\10_4.jpg
> 
> 难道是 读取了xml的地址 10_4.xml F:\00Biaozhu\OK\10_4.jpg
> 
> F:\00Biaozhu\OK 已经被删除
> 
> @linhandev

这块我们从xml中解析文件路径的方式可以参考[这里](https://github.com/PaddleCV-SIG/PaddleLabel/blob/v0.1.0/doc/CN/project/detection.md#pascal-voc)。

并将该标签与位于`/数据集路径/folder/filename`的图像文件匹配

感觉你这个xml应该是里面是有folder，叫Ok，所以导入的时候会看到pdlabel在找一个带ok路径的图片。

话说你这个voc的数据集是用什么工具做的啊，不同的工具对这些项的写法都有些不同。

**Comment by monkeycc** [comment]
数据增强了样本
但是没改这个folder的地址

应该是这个问题

我自己改改我的脚本好了

**Comment by linhandev** [comment]
感觉voc的问题比coco多。这块大概有三个方案
- 根据xml里面的folder和filename完整匹配 （现在的方案）
- 只根据xml里面的filename匹配
- 根据train_list.txt这种外部文件匹配

你觉得哪个会兼容性更好点

**Comment by linhandev** [comment]
第三个一些工具导出的时候应该没有，第一个我感觉好像不是所有工具都用folder这个项

**Comment by monkeycc** [comment]
根据train_list.txt这种外部文件匹配

这个好
PaddleX就是用这个方式

比如我在我家标注
把数据集发给你

结果xml地址 不对 
根据xml里面的folder和filename完整匹配 （现在的方案）
只根据xml里面的filename匹配

导致数据集用不了

**Comment by linhandev** [comment]
嗯，这样是额外的文件。刚才这个场景的话方案二倒是也可以处理，大家的路径甚至数据集文件夹下存图的那个文件夹都可以不一样，但是只要文件名对的上就对得上。

我感觉可以结合二三，先做三， 剩下的图再做一下二。

**Comment by monkeycc** [comment]
辛苦了
搞起来

不过WEB
画框
确实难用~~

**Comment by linhandev** [comment]
> 辛苦了
> 搞起来
> 
> 不过WEB
> 画框
> 确实难用~~

最近快发新版了，话说那个action的版本拉框还很难用吗，我感觉有不少提升🤔

web确实没有qt好优化效率

**Comment by monkeycc** [comment]
`https://github.com/open-mmlab/labelbee`
隔壁家的 标注工具  前端相对流畅一点
特别是人家打包的桌面端   很流畅

label-studio
也难用 但是起码能实现按键画框

**Comment by linhandev** [comment]
当时没用labelbee前端感觉太亏了 /笑哭

label studio前端感觉很一般，api倒是觉得设计不错，拓展行很好

**Comment by linhandev** [comment]
voc这块目前的导入逻辑参考[这里](https://paddlecv-sig.github.io/PaddleLabel/CN/project/detection.html#%E7%9B%AE%E6%A0%87%E6%A3%80%E6%B5%8B%E6%A0%87%E6%B3%A8) 首先看txt列表，之后按照文件名对应，最后看xml内容，感觉应该解决了这个issue描述的问题，大佬有空可以看看，没问题的话这个issue应该可以close了
