### ISSUE TITLE
XML坐标是浮点数会报错,ValueError: invalid literal for int() with base 10: '495.6576232910156'

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#81]
导入VOC数据
XML坐标是浮点数会报错
```
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
[ERROR]detection.449: Image size read from disk 1,1280,1024,3 isn't the same with parsed from pascal xml 1,1280,1024
Create project failed
Traceback (most recent call last):
  File "D:\anaconda308\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\anaconda308\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
    importer(data_dir)
  File "D:\anaconda308\lib\site-packages\paddlelabel\task\detection.py", line 442, in voc_importer
    data, labels = parse_voc_label(osp.join(base_dir, label_path))
  File "D:\anaconda308\lib\site-packages\paddlelabel\task\detection.py", line 69, in parse_voc_label
    r = [int(t) for t in r]
  File "D:\anaconda308\lib\site-packages\paddlelabel\task\detection.py", line 69, in <listcomp>
    r = [int(t) for t in r]
ValueError: invalid literal for int() with base 10: '495.6576232910156'
```

**Comment by linhandev** [comment]
已经修复，将在近期发布下个版本
