### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by YasinZhao** [PaddleCV-SIG/PP-Label#87]
如题，请问这种是因为环境问题导致的吗，该如何解决？
系统环境：mac
python环境：anaconda python=3.9

Traceback (most recent call last):
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/bin/pdlabel", line 5, in <module>
    from paddlelabel.__main__ import run
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/paddlelabel/__main__.py", line 6, in <module>
    from paddlelabel.serve import connexion_app
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/paddlelabel/serve.py", line 23, in <module>
    db.create_all()
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "/Users/yi.zhao/opt/anaconda3/envs/paddlelabel/lib/python3.9/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by linhandev** [comment]
应该是 Flask-SQLAlchemy 包版本过高导致的，可以尝试
```shell
pip install Flask-SQLAlchemy==2.5.1
```
之后再启动。目前在解决这个问题

**Comment by YasinZhao** [comment]
> 

确实是版本过高的问题，已解决，谢谢~
