### ISSUE TITLE
paddlelabel打开时报错，请问如何解决？

### ISSUE THREAD

**Issue by GGGJOY** [PaddleCV-SIG/PP-Label#88]
根据安装教程进行到最后一步，具体如下：
(eiseg_env2) E:\eiseg>paddlelabel
Database path: sqlite:///C:\Users\Administrator\.paddlelabel\paddlelabel.db
Creating db
Traceback (most recent call last):
  File "E:\anaconda\main\envs\eiseg_env2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda\main\envs\eiseg_env2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\main\envs\eiseg_env2\Scripts\paddlelabel.exe\__main__.py", line 4, in <module>
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\paddlelabel\__main__.py", line 6, in <module>
    from paddlelabel.serve import connexion_app
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\paddlelabel\serve.py", line 23, in <module>
    db.create_all()
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\flask_sqlalchemy\extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\flask_sqlalchemy\extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\flask_sqlalchemy\extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "E:\anaconda\main\envs\eiseg_env2\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by linhandev** [comment]
请参考这个issue #87 @GGGJOY
