### ISSUE TITLE
数据划分问题

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#93]
选择 70% 20% 10%

报错
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]detection.449: Image size read from disk 1,2448,2048,3 isn't the same with parsed from pascal xml 1,2448,2048
[ERROR]app.1741: Exception on /api/projects/1/split [POST]
Traceback (most recent call last):
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\decorator.py", line 68, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\validation.py", line 196, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\validation.py", line 399, in wrapper
    return function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\paddlelabel\api\controller\project.py", line 210, in split_dataset
    tasks[idx].set = set
IndexError: list index out of range
[ERROR]app.1741: Exception on /api/projects/1/split [POST]
Traceback (most recent call last):
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\decorator.py", line 68, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\validation.py", line 196, in wrapper
    response = function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\validation.py", line 399, in wrapper
    return function(request)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\connexion\decorators\parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "D:\anaconda31114\envs\paddlelabel\lib\site-packages\paddlelabel\api\controller\project.py", line 210, in split_dataset
    tasks[idx].set = set
IndexError: list index out of range
```

默认的
60% 20% 20%不会报错

**Comment by linhandev** [comment]
奇怪，我这两天还用来着，数据总数是多少呢

**Comment by monkeycc** [comment]
92张图片

**Comment by linhandev** [comment]
应该是有一个四舍五入有问题，试试这个

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3470910643

下这个

![image](https://user-images.githubusercontent.com/29757093/201934127-cf2e6490-4bf0-4327-9678-383b11dbb3ec.png)

**Comment by monkeycc** [comment]
测试通过
确实是这个问题
